name: kozachok_admin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  auto_route: ^7.7.1
  auto_route_generator: ^7.2.0
  rxdart: ^0.27.7
  intl: ^0.18.0
  firebase_storage: ^11.2.6
  json_annotation: ^4.8.1
  image_picker_for_web: ^3.0.1
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.0.0
  firebase_storage_web: ^3.6.6
  firebase_core_web: ^2.7.0
  file_picker: ^5.5.0
  shared_preferences: ^2.2.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  web_image_downloader: ^1.0.1
  image_downloader_web: ^2.0.4
  image_picker_web: ^3.1.1
  flutter_dropzone: ^3.0.6
  drop_zone: ^1.0.2
  image_cropper: ^5.0.1
  crop_your_image: ^0.7.5
  crop: ^0.5.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Bold.ttf
        - asset: fonts/Gotham-Book.ttf
        - asset: fonts/Gotham-Medium.ttf


flutter_gen:
  output: lib/generated/
  line_length: 80

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true