// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEUsGC_Tm_jECrXtw2jK1MVWkVjiKU24c',
    appId: '1:716568401326:android:59b3046b7067625c8c243f',
    messagingSenderId: '716568401326',
    projectId: 'ai-gptchat',
    storageBucket: 'ai-gptchat.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAQ7gxEh240lw8KnYYmfkvVmXQ4OVnoVi4",
      authDomain: "radiokozachok-fe8cd.firebaseapp.com",
      projectId: "radiokozachok-fe8cd",
      storageBucket: "radiokozachok-fe8cd.appspot.com",
      messagingSenderId: "467057549060",
      appId: "1:467057549060:web:7f9cb6f28d15e671e3ba51",
      measurementId: "G-Z8PBKZS0PB");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeMGPDjbCZbLWDBMmucBxRUxxuU5Nhl4',
    appId: '1:716568401326:ios:069db6aa6f8e37d38c243f',
    messagingSenderId: '716568401326',
    projectId: 'ai-gptchat',
    storageBucket: 'ai-gptchat.appspot.com',
    androidClientId:
        '716568401326-0i0hmhrl1pvpohac8hq0i5k2po80c68d.apps.googleusercontent.com',
    iosClientId:
        '716568401326-7plflbv7m2vppn0bpj7bld6cppmu7hts.apps.googleusercontent.com',
    iosBundleId: 'com.aichat.chatbot.assistant',
  );
}
